apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect-agent.fullname" . }}
  labels:
    {{- include "prefect-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prefect-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prefect-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prefect-agent.serviceAccountName" . }}
      containers:
      - env:
        - name: LIBERATOR_REST_HOST
          value: 10.12.32.22
        - name: LIBERATOR_REST_PORT
          value: "47753"
        - name: LIBERATOR_SYSTEM
          value: Prefect
        - name: LIBERATOR_TOKEN
          value: {{ .Values.liberator.token }}
        - name: LIBERATOR_USER
          value: {{ .Values.liberator.user | default .Release.Namespace }}
        - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
          value: {{ .Values.prefect.api_key }}
        - name: USER
          value: {{ .Release.Namespace }}
        - name: PREFECT__CLOUD__AGENT__NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: PREFECT__CLOUD__API_KEY
          valueFrom:
            secretKeyRef:
              key: PREFECT__CLOUD__API_KEY
              name: {{ include "prefect-agent.fullname" . }}
        - name: PREFECT__CLOUD__TENANT_ID
          value: ''
        - name: PREFECT__CLOUD__AGENT__LABELS
          value: '["{{.Release.Namespace}}", "{{ .Values.prefect.label }}"]'
        - name: USER_PREFECT_ENV
          value: {{ .Values.prefect.condaEnv }}
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: IfNotPresent
        name: agent
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        volumeMounts:
          - mountPath: /home/cloudQuant/anaconda3
            name: prefect-nfs
            readOnly: true
            subPath: home/cloudQuant/anaconda3
          - mountPath: /home/{{.Release.Namespace}}
            name: prefect-nfs
            subPath: home/{{.Release.Namespace}}
          - mountPath: /home/jovyan
            name: prefect-nfs
            subPath: home/{{.Release.Namespace}}
          - mountPath: /var/data/shared/profile
            name: prefect-nfs
            readOnly: true
            subPath: var_data/shared/profile
      volumes:
        - name: prefect-nfs
          nfs:
            path: /volume1/cqspace
            server: cqnfs