---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prefect-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "prefect-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - events
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "prefect-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prefect-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "prefect-agent.serviceAccountName" . }}