apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prefect-agent.fullname" . }}
  labels:
    {{- include "prefect-agent.labels" . | nindent 4 }}
data:
  PREFECT__CLOUD__API_KEY: {{ .Values.prefect.api_key | b64enc | quote }}
