apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
data:
  jupyter_notebook_config.py: |-
    c.NotebookApp.token = ''
    c.NotebookApp.password = u''
    c.NotebookApp.ip = '*'
  ipython_config.py: |-
    c.HistoryAccessor.hist_file = '/tmp/ipython_hist.sqlite'
    c.HistoryManager.hist_file = '/tmp/ipython_hist.sqlite'